### ISSUE TITLE
Can't remove rbenv from modeline

### ISSUE THREAD

**Issue by squiter** [senny/rbenv.el#14]
Hi! :)

I already set `rbenv-show-active-ruby-in-modeline` to `nil` but don't work.  
I tried `(setq rbenv-modeline-function 'rbenv--modeline-plain)` to remove colors at least, but don't work too.
I'm running GNU Emacs 24.5.5 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2015-07-13 on Atago.local.
Can you help me?

**Comment by senny** [comment]
mmm that's interesting. I just double checked and the configuration options still work for me. Did you set them before activating the rbenv global mode (eg. `(global-rbenv-mode)`)? Does deactivating and reactivating that mode have any effect:

```emacslisp
(global-rbenv-mode)
(global-rbenv-mode)
```

**Comment by squiter** [comment]
No, I'm setting after global... 

This is my rbenv configurations:

```lisp
;;; init-rbenv.el --- My configration for Rbenv
;;; Commentary:
;;; Code:

(require 'rbenv)

(setq rbenv-installation-dir "/usr/local")

(global-rbenv-mode)

(setq rbenv-modeline-function 'rbenv--modeline-plain)
(setq rbenv-show-active-ruby-in-modeline nil)

(provide 'init-rbenv)
;;; init-rbenv.el ends here
```

I tried to duplicate the line with `(global-rbenv-mode)` like your example, but don't work too.

**Comment by senny** [comment]
@squiter you need to set it in advance...

**Comment by squiter** [comment]
Ahh sorry man! Set global rbenv mode after the configs works fine for me!

Thank you!

**Comment by andrewmelis** [comment]
thanks. this helped me as well.
