### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by lafrenierejm** [senny/rbenv.el#19]
As of this writing the last commit was in 2014. Is this repository still being maintained? If not, would you have any objections to the community (either myself or anyone else who is interested) reaching out to the melpa maintainers to promote a fork?

**Comment by senny** [comment]
Hi @lafrenierejm, the repository is not actively maintained. I have no objections to grant commit permissions to someone who is interested in continuing the project. I am not familiar enough with melpa to know if I can grant other's the permission to publish as well. If not, I'm happy to publish whenever it's necessary.

**Comment by senny** [comment]
I just double checked and I believe MELPA is just based on the source on GitHub, granting commit permissions should be enough to keep the ball rolling then.

**Comment by lafrenierejm** [comment]
> I just double checked and I believe MELPA is just based on the source on GitHub, granting commit permissions should be enough to keep the ball rolling then.

Correct, MELPA just uses Git directly.

I would be glad to help maintain if that would be helpful, though I only work with Ruby occasionally and am far from an expert on the ecosystem. I'd also be glad to try to help find other maintainers, regardless of whether or not I also become one. Just LMK how I can be of most help!

**Comment by jmay** [comment]
@senny I'm also willing to pick up support for this package. Regular emacs user, regular ruby user, regular rbenv user.
