### ISSUE TITLE
Symbol’s function definition is void: reduce

### ISSUE THREAD

**Issue by CyJimmy264** [senny/rbenv.el#20]
On a new Emacs 29.1 receiving this messages in \*Warnings\*

```
⛔ Error (use-package): ruby-mode/:init: Symbol’s function definition is void: reduce
⛔ Warning (comp): rbenv.el:141:11: Warning: assignment to free variable ‘eshell-path-env’
⛔ Warning (comp): rbenv.el:151:11: Warning: assignment to free variable ‘eshell-path-env’
⛔ Warning (comp): rbenv.el:171:2: Warning: docstring wider than 80 characters
⛔ Warning (comp): rbenv.el:206:20: Warning: defcustom for ‘global-rbenv-mode’ fails to specify containing group
⛔ Warning (comp): rbenv.el:50:4: Warning: the function ‘reduce’ is not known to be defined.
```

To workaround it, I've rollbacked the previous version of `defun rbenv--expand-path` without `reduce`:
```
(defun rbenv--expand-path (&rest segments)
  "Expand SEGMENTS relative to the install dir."
  (let ((path (mapconcat 'identity segments "/"))
        (installation-dir (replace-regexp-in-string "/$" "" rbenv-installation-dir)))
    (expand-file-name path rbenv-installation-dir)))
```

I'm not elisp-er, so what is the right way to solve it?

**Comment by littlemove** [comment]
I've experienced the same. It seems that using the elisp function `cl-reduce` instead should do the trick. I couldn't find traces of the existence of `reduce` as an elisp function, neither of its deprecation...

I can make a pull request if @senny or whoever is maintaining the repo agrees, and sheds some light.

**Comment by lafrenierejm** [comment]
> I've experienced the same. It seems that using the elisp function `cl-reduce` instead should do the trick. I couldn't find traces of the existence of `reduce` as an elisp function, neither of its deprecation...
> 
> 
> 
> I can make a pull request if @senny or whoever is maintaining the repo agrees, and sheds some light.

If you'd be willing to raise a PR to use `cl-reduce`, I'd be glad to merge it!

**Comment by lafrenierejm** [comment]
This was my bad. I had an alias for `cl-reduce` in my config without realizing it. I apologize for the inconvenience.
